### ISSUE TITLE
Wrong version in master branch ?

### ISSUE THREAD

**Issue by chris-zen** [scrapinghub/aduana#17]
The version in setup.py in the master branch (0.2.1) is the same than the one in PyPI (https://pypi.python.org/pypi/aduana/0.2.1), but the code has changed. Shouldn't it be 0.2.2 or 0.3 instead so there is no confusion ?

I realized of that while trying to evaluate the FreqScheduler but the import failed, then cloned the master branch and the import worked.

**Comment by plafl** [comment]
True, updated to 0.2.2
