### ISSUE TITLE
Request.meta.score not optional

### ISSUE THREAD

**Issue by chris-zen** [scrapinghub/aduana#19]
The documentation says that the score metadata is optional but the backend fails if not specified.

Offender code here:
https://github.com/scrapinghub/aduana/blob/master/aduana/frontera.py#L64

**Comment by plafl** [comment]
Yes. The score for the crawled page is optional but the scores for the (uncrawled) links are required. I don't think this makes sense so I have [changed the code](https://github.com/scrapinghub/aduana/commit/b14bb32f9b92393db241733f94d06a286525a3c1). If no score is provided a default of 0.0 is assumed.
