### ISSUE TITLE
Allow to specify scores for the seeds

### ISSUE THREAD

**Issue by chris-zen** [scrapinghub/aduana#21]
Our seeds are determined by a classifier which produces some kind of confidence/probability, and I would like to use it as a score for the initial seeds.

I see here that it is initialized to 1.0:
https://github.com/scrapinghub/aduana/blob/master/aduana/frontera.py#L53

But looks like easy to check first whether it contains an score in its meta or not.

Any idea on how complex would it be ?
Thanks.

**Comment by plafl** [comment]
The change in Aduana is very simple, and I have already [commited it](https://github.com/scrapinghub/aduana/commit/18ffb3fdb0a73175b4bbb829bb511c8aa522eb15). 
But you also need to make sure [Frontera loads the scores](http://frontera.readthedocs.org/en/latest/topics/seed-loaders.html?highlight=seeds) and stores them in the link metadata.

**Comment by chris-zen** [comment]
Thanks :-)
