### ISSUE TITLE
Add python tests

### ISSUE THREAD

**Issue by plafl** [scrapinghub/aduana#6]
All tests are right now performed at the C library level.

**Comment by kmike** [comment]
What about writing all tests in Python?

**Comment by plafl** [comment]
My plan for the future is to test almost everything in python. This way I test the python code too and also the tests are more pleasant to write. I will keep the existing C tests anyway and I will add tests in C only if I'm not sure if the error is in the python wrappers or the C code.

**Comment by plafl** [comment]
Added first tests in 9d03218619d96faabcac894e6b54ed9868948be9
